### ISSUE TITLE
zip+run doesnt work on cygwin+bash

### ISSUE THREAD

**Issue by mcooper7290** [mvysny/vaadin14-embedded-jetty-gradle#2]
I'm trying to run this sample in production mode but its not working:

```
[mcooper@oberon ~/ws/cmb/develop/vaadin14-embedded-jetty-gradle]$ gr build -Pvaadin.productionMode
> Task :compileJava
> Task :vaadinPrepareFrontend
> Task :processResources
> Task :classes
> Task :vaadinBuildFrontend
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :zip
> Task :assemble
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
> Task :check
> Task :build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 7s
11 actionable tasks: 11 executed
[mcooper@oberon ~/ws/cmb/develop/vaadin14-embedded-jetty-gradle]$ cd build/distributions/
[mcooper@oberon ~/ws/cmb/develop/vaadin14-embedded-jetty-gradle/build/distributions]$ unzip vaadin14-embedded-jetty-gradle.zip
Archive:  vaadin14-embedded-jetty-gradle.zip
  inflating: run
  inflating: run.bat
   creating: libs/
  inflating: libs/vaadin14-embedded-jetty-gradle.jar
[mcooper@oberon ~/ws/cmb/develop/vaadin14-embedded-jetty-gradle/build/distributions]$ dos2unix run
dos2unix: converting file run to Unix format...
[mcooper@oberon ~/ws/cmb/develop/vaadin14-embedded-jetty-gradle/build/distributions]$ bash -x run
+ set -e -o pipefail
++ ls libs/vaadin14-embedded-jetty-gradle.jar
++ tr '\n' :
+ CP=libs/vaadin14-embedded-jetty-gradle.jar:
+ java -cp libs/vaadin14-embedded-jetty-gradle.jar: com.vaadin.starter.skeleton.ManualJetty
Error: Could not find or load main class com.vaadin.starter.skeleton.ManualJetty
[mcooper@oberon ~/ws/cmb/develop/vaadin14-embedded-jetty-gradle/build/distributions]$ java -cp libs/vaadin14-embedded-jetty-gradle.jar com.vaadin.starter.skeleton.ManualJetty
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/servlet/ServletContextHandler
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.servlet.ServletContextHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
[mcooper@oberon ~/ws/cmb/develop/vaadin14-embedded-jetty-gradle/build/distributions]$
```

This is the first time I've tried this with the sample.  I'm having problems with my own vaadin14 code running production from jar and so I was trying to use this as a sample.

I did do a fresh git pull so I'm running the latest version of the sample.

**Comment by mvysny** [comment]
You're right - thank you for letting me know. The problem was that the `libs/` folder was not populated - it lacked all transitive dependency jars.

The problem is that when I started to use the `api`/`implementation` dependencies instead of the `compile` ones, the `runtime` configuration was suddenly empty. The fix was to populate the zip file with the contents of the `runtimeClasspath` confuguration.

**Comment by mcooper7290** [comment]
It still isn't working for me.  After "gradle clean build -Pvaadin.productionMode" and unzip I get:

```
$ bash -x run
+ set -e -o pipefail
++ ls libs/asm-7.2.jar libs/asm-analysis-7.2.jar libs/asm-commons-7.2.jar libs/asm-tree-7.2.jar libs/atmosphere-runtime-2.4.30.slf4jvaadin1.jar libs/byte-buddy-1.10.9.jar libs/commons-codec-1.9.jar libs/commons-compress-1.19.jar libs/commons-fileupload-1.3.3.jar libs/commons-io-2.5.jar libs/commons-lang3-3.0.jar libs/commons-logging-1.2.jar libs/flow-client-2.2.0.jar libs/flow-data-2.2.0.jar libs/flow-dnd-2.2.0.jar libs/flow-html-components-2.2.0.jar libs/flow-push-2.2.0.jar libs/flow-server-2.2.0.jar libs/gentyref-1.2.0.vaadin1.jar libs/gwt-elemental-2.8.2.vaadin2.jar libs/httpclient-4.5.2.jar libs/httpcore-4.4.4.jar libs/javax.annotation-api-1.3.jar libs/javax.servlet-api-3.1.0.jar libs/javax.websocket-api-1.0.jar libs/javax-websocket-client-impl-9.4.28.v20200408.jar libs/javax-websocket-server-impl-9.4.28.v20200408.jar libs/jetty-annotations-9.4.28.v20200408.jar libs/jetty-client-9.4.28.v20200408.jar libs/jetty-continuation-9.4.28.v20200408.jar libs/jetty-http-9.4.28.v20200408.jar libs/jetty-io-9.4.28.v20200408.jar libs/jetty-jndi-9.4.28.v20200408.jar libs/jetty-plus-9.4.28.v20200408.jar libs/jetty-security-9.4.28.v20200408.jar libs/jetty-server-9.4.28.v20200408.jar libs/jetty-servlet-9.4.28.v20200408.jar libs/jetty-util-9.4.28.v20200408.jar libs/jetty-webapp-9.4.28.v20200408.jar libs/jetty-xml-9.4.28.v20200408.jar libs/jsoup-1.12.1.jar libs/mobile-drag-drop-2.3.0-rc.1.jar libs/ph-commons-9.1.2.jar libs/ph-css-6.1.1.jar libs/slf4j-api-1.7.30.jar libs/slf4j-simple-1.7.30.jar libs/vaadin__vaadin-mobile-drag-drop-1.0.0.jar libs/vaadin14-embedded-jetty-gradle.jar libs/vaadin-accordion-flow-2.0.0.jar libs/vaadin-app-layout-flow-2.0.5.jar libs/vaadin-button-flow-2.0.2.jar libs/vaadin-checkbox-flow-2.0.5.jar libs/vaadin-combo-box-flow-3.0.9.jar libs/vaadin-context-menu-flow-3.1.2.jar libs/vaadin-core-14.2.0.jar libs/vaadin-custom-field-flow-3.0.4.jar libs/vaadin-date-picker-flow-2.0.8.jar libs/vaadin-date-time-picker-flow-1.0.0.jar libs/vaadin-details-flow-2.0.0.jar libs/vaadin-dialog-flow-2.1.0.jar libs/vaadin-form-layout-flow-2.0.3.jar libs/vaadin-grid-flow-4.1.4.jar libs/vaadin-icons-flow-2.0.3.jar libs/vaadin-iron-list-flow-2.0.0.jar libs/vaadin-list-box-flow-2.1.1.jar libs/vaadin-login-flow-2.0.0.jar libs/vaadin-lumo-theme-2.2.0.jar libs/vaadin-material-theme-2.2.0.jar libs/vaadin-menu-bar-flow-1.0.3.jar libs/vaadin-notification-flow-2.0.0.jar libs/vaadin-ordered-layout-flow-2.1.0.jar libs/vaadin-progress-bar-flow-2.0.2.jar libs/vaadin-radio-button-flow-2.0.4.jar libs/vaadin-select-flow-2.0.3.jar libs/vaadin-split-layout-flow-2.0.3.jar libs/vaadin-tabs-flow-2.0.4.jar libs/vaadin-text-field-flow-2.1.1.jar libs/vaadin-time-picker-flow-2.1.0.jar libs/vaadin-upload-flow-2.1.0.jar libs/validation-api-2.0.0.Final.jar libs/websocket-api-9.4.28.v20200408.jar libs/websocket-client-9.4.28.v20200408.jar libs/websocket-common-9.4.28.v20200408.jar libs/websocket-server-9.4.28.v20200408.jar libs/websocket-servlet-9.4.28.v20200408.jar
++ tr '\n' :
+ CP=libs/asm-7.2.jar:libs/asm-analysis-7.2.jar:libs/asm-commons-7.2.jar:libs/asm-tree-7.2.jar:libs/atmosphere-runtime-2.4.30.slf4jvaadin1.jar:libs/byte-buddy-1.10.9.jar:libs/commons-codec-1.9.jar:libs/commons-compress-1.19.jar:libs/commons-fileupload-1.3.3.jar:libs/commons-io-2.5.jar:libs/commons-lang3-3.0.jar:libs/commons-logging-1.2.jar:libs/flow-client-2.2.0.jar:libs/flow-data-2.2.0.jar:libs/flow-dnd-2.2.0.jar:libs/flow-html-components-2.2.0.jar:libs/flow-push-2.2.0.jar:libs/flow-server-2.2.0.jar:libs/gentyref-1.2.0.vaadin1.jar:libs/gwt-elemental-2.8.2.vaadin2.jar:libs/httpclient-4.5.2.jar:libs/httpcore-4.4.4.jar:libs/javax.annotation-api-1.3.jar:libs/javax.servlet-api-3.1.0.jar:libs/javax.websocket-api-1.0.jar:libs/javax-websocket-client-impl-9.4.28.v20200408.jar:libs/javax-websocket-server-impl-9.4.28.v20200408.jar:libs/jetty-annotations-9.4.28.v20200408.jar:libs/jetty-client-9.4.28.v20200408.jar:libs/jetty-continuation-9.4.28.v20200408.jar:libs/jetty-http-9.4.28.v20200408.jar:libs/jetty-io-9.4.28.v20200408.jar:libs/jetty-jndi-9.4.28.v20200408.jar:libs/jetty-plus-9.4.28.v20200408.jar:libs/jetty-security-9.4.28.v20200408.jar:libs/jetty-server-9.4.28.v20200408.jar:libs/jetty-servlet-9.4.28.v20200408.jar:libs/jetty-util-9.4.28.v20200408.jar:libs/jetty-webapp-9.4.28.v20200408.jar:libs/jetty-xml-9.4.28.v20200408.jar:libs/jsoup-1.12.1.jar:libs/mobile-drag-drop-2.3.0-rc.1.jar:libs/ph-commons-9.1.2.jar:libs/ph-css-6.1.1.jar:libs/slf4j-api-1.7.30.jar:libs/slf4j-simple-1.7.30.jar:libs/vaadin__vaadin-mobile-drag-drop-1.0.0.jar:libs/vaadin14-embedded-jetty-gradle.jar:libs/vaadin-accordion-flow-2.0.0.jar:libs/vaadin-app-layout-flow-2.0.5.jar:libs/vaadin-button-flow-2.0.2.jar:libs/vaadin-checkbox-flow-2.0.5.jar:libs/vaadin-combo-box-flow-3.0.9.jar:libs/vaadin-context-menu-flow-3.1.2.jar:libs/vaadin-core-14.2.0.jar:libs/vaadin-custom-field-flow-3.0.4.jar:libs/vaadin-date-picker-flow-2.0.8.jar:libs/vaadin-date-time-picker-flow-1.0.0.jar:libs/vaadin-details-flow-2.0.0.jar:libs/vaadin-dialog-flow-2.1.0.jar:libs/vaadin-form-layout-flow-2.0.3.jar:libs/vaadin-grid-flow-4.1.4.jar:libs/vaadin-icons-flow-2.0.3.jar:libs/vaadin-iron-list-flow-2.0.0.jar:libs/vaadin-list-box-flow-2.1.1.jar:libs/vaadin-login-flow-2.0.0.jar:libs/vaadin-lumo-theme-2.2.0.jar:libs/vaadin-material-theme-2.2.0.jar:libs/vaadin-menu-bar-flow-1.0.3.jar:libs/vaadin-notification-flow-2.0.0.jar:libs/vaadin-ordered-layout-flow-2.1.0.jar:libs/vaadin-progress-bar-flow-2.0.2.jar:libs/vaadin-radio-button-flow-2.0.4.jar:libs/vaadin-select-flow-2.0.3.jar:libs/vaadin-split-layout-flow-2.0.3.jar:libs/vaadin-tabs-flow-2.0.4.jar:libs/vaadin-text-field-flow-2.1.1.jar:libs/vaadin-time-picker-flow-2.1.0.jar:libs/vaadin-upload-flow-2.1.0.jar:libs/validation-api-2.0.0.Final.jar:libs/websocket-api-9.4.28.v20200408.jar:libs/websocket-client-9.4.28.v20200408.jar:libs/websocket-common-9.4.28.v20200408.jar:libs/websocket-server-9.4.28.v20200408.jar:libs/websocket-servlet-9.4.28.v20200408.jar:
+ java -cp libs/asm-7.2.jar:libs/asm-analysis-7.2.jar:libs/asm-commons-7.2.jar:libs/asm-tree-7.2.jar:libs/atmosphere-runtime-2.4.30.slf4jvaadin1.jar:libs/byte-buddy-1.10.9.jar:libs/commons-codec-1.9.jar:libs/commons-compress-1.19.jar:libs/commons-fileupload-1.3.3.jar:libs/commons-io-2.5.jar:libs/commons-lang3-3.0.jar:libs/commons-logging-1.2.jar:libs/flow-client-2.2.0.jar:libs/flow-data-2.2.0.jar:libs/flow-dnd-2.2.0.jar:libs/flow-html-components-2.2.0.jar:libs/flow-push-2.2.0.jar:libs/flow-server-2.2.0.jar:libs/gentyref-1.2.0.vaadin1.jar:libs/gwt-elemental-2.8.2.vaadin2.jar:libs/httpclient-4.5.2.jar:libs/httpcore-4.4.4.jar:libs/javax.annotation-api-1.3.jar:libs/javax.servlet-api-3.1.0.jar:libs/javax.websocket-api-1.0.jar:libs/javax-websocket-client-impl-9.4.28.v20200408.jar:libs/javax-websocket-server-impl-9.4.28.v20200408.jar:libs/jetty-annotations-9.4.28.v20200408.jar:libs/jetty-client-9.4.28.v20200408.jar:libs/jetty-continuation-9.4.28.v20200408.jar:libs/jetty-http-9.4.28.v20200408.jar:libs/jetty-io-9.4.28.v20200408.jar:libs/jetty-jndi-9.4.28.v20200408.jar:libs/jetty-plus-9.4.28.v20200408.jar:libs/jetty-security-9.4.28.v20200408.jar:libs/jetty-server-9.4.28.v20200408.jar:libs/jetty-servlet-9.4.28.v20200408.jar:libs/jetty-util-9.4.28.v20200408.jar:libs/jetty-webapp-9.4.28.v20200408.jar:libs/jetty-xml-9.4.28.v20200408.jar:libs/jsoup-1.12.1.jar:libs/mobile-drag-drop-2.3.0-rc.1.jar:libs/ph-commons-9.1.2.jar:libs/ph-css-6.1.1.jar:libs/slf4j-api-1.7.30.jar:libs/slf4j-simple-1.7.30.jar:libs/vaadin__vaadin-mobile-drag-drop-1.0.0.jar:libs/vaadin14-embedded-jetty-gradle.jar:libs/vaadin-accordion-flow-2.0.0.jar:libs/vaadin-app-layout-flow-2.0.5.jar:libs/vaadin-button-flow-2.0.2.jar:libs/vaadin-checkbox-flow-2.0.5.jar:libs/vaadin-combo-box-flow-3.0.9.jar:libs/vaadin-context-menu-flow-3.1.2.jar:libs/vaadin-core-14.2.0.jar:libs/vaadin-custom-field-flow-3.0.4.jar:libs/vaadin-date-picker-flow-2.0.8.jar:libs/vaadin-date-time-picker-flow-1.0.0.jar:libs/vaadin-details-flow-2.0.0.jar:libs/vaadin-dialog-flow-2.1.0.jar:libs/vaadin-form-layout-flow-2.0.3.jar:libs/vaadin-grid-flow-4.1.4.jar:libs/vaadin-icons-flow-2.0.3.jar:libs/vaadin-iron-list-flow-2.0.0.jar:libs/vaadin-list-box-flow-2.1.1.jar:libs/vaadin-login-flow-2.0.0.jar:libs/vaadin-lumo-theme-2.2.0.jar:libs/vaadin-material-theme-2.2.0.jar:libs/vaadin-menu-bar-flow-1.0.3.jar:libs/vaadin-notification-flow-2.0.0.jar:libs/vaadin-ordered-layout-flow-2.1.0.jar:libs/vaadin-progress-bar-flow-2.0.2.jar:libs/vaadin-radio-button-flow-2.0.4.jar:libs/vaadin-select-flow-2.0.3.jar:libs/vaadin-split-layout-flow-2.0.3.jar:libs/vaadin-tabs-flow-2.0.4.jar:libs/vaadin-text-field-flow-2.1.1.jar:libs/vaadin-time-picker-flow-2.1.0.jar:libs/vaadin-upload-flow-2.1.0.jar:libs/validation-api-2.0.0.Final.jar:libs/websocket-api-9.4.28.v20200408.jar:libs/websocket-client-9.4.28.v20200408.jar:libs/websocket-common-9.4.28.v20200408.jar:libs/websocket-server-9.4.28.v20200408.jar:libs/websocket-servlet-9.4.28.v20200408.jar: com.vaadin.starter.skeleton.ManualJetty
Error: Could not find or load main class com.vaadin.starter.skeleton.ManualJetty
```

What's strange is the class is present:
```
$ jar tf vaadin14-embedded-jetty-gradle.jar | grep ManualJetty
com/vaadin/starter/skeleton/ManualJetty.class
```

**Comment by mvysny** [comment]
Hmm unfortunately I can not reproduce the issue on my machine anymore.

 I wonder, could there be a limit to the length of the command in bash? E.g. if the class path is cut somewhere and lacks the vaadin14-embedded-jetty-gradle.jar then that could cause the issue to manifest.

Which bash version/Linux are you using please?

**Comment by mcooper7290** [comment]
I'm using bash 4.2.46(2) on cygwin.

If I launch with "run.bat" from powershell it does work.

**Comment by mvysny** [comment]
Cygwin could be the culprit here. Unfortunately I don't have a windows machine to test right now, but I can check couple of cygwin workarounds which might apply to this case.

**Comment by mvysny** [comment]
Perhaps let's try replacing colon with semicolon: https://stackoverflow.com/questions/9690756/how-to-run-java-from-cygwin

Makes sense since we're running java.exe which expects windows-style separators ;

**Comment by mcooper7290** [comment]
Yes that makes sense now.  The "java" executable is built for Windows so it expects Windows pathnames and $CLASSPATH to use semi-colons.  So its reasonable to say that "run" is only supported on true linux/unix, not cygwin.

I think the real solution would be to put all the CLASSPATH entries into MANIFEST.MF as "Class-Path".  That is far more portable and less prone to long command line problems than using "java -cp " and giving every jar.

**Comment by mvysny** [comment]
I've now refactored the build system to use the scripts generated by Gradle Application plugin. Could you please try the new scripts out and let me know whether it works properly?

Regarding the CLASSPATH entry: I wonder whether there's a way to configure the Gradle Application plugin to create those? I tried to look at https://docs.gradle.org/current/userguide/application_plugin.html but failed to find such code.
