### ISSUE TITLE
DevMode doesn't work

### ISSUE THREAD

**Issue by manitas-manitas** [mvysny/vaadin14-embedded-jetty-gradle#8]
Hi

if I clone the master branch and run ./gradlew run  I have the following error message
Any idea ?

Thank you

FYI production mode works

    2021-11-10 10:04:53.010 [qtp586084331-19] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
    com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.
            at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:956)
            at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupDocumentHead(BootstrapHandler.java:833)
            at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:600)
            at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:514)
            at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
            at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1559)
            at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
            at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
            at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
            at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
            at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
            at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
            at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
            at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
            at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
            at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
            at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
            at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
            at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
            at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
            at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
            at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
            at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
            at org.eclipse.jetty.server.Server.handle(Server.java:516)
            at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
            at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
            at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
            at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
            at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
            at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
            at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
            at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
            at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
            at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
            at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.net.ConnectException: Connection refused
            at java.base/sun.nio.ch.Net.pollConnect(Native Method)
            at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
            at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
            at java.base/java.net.Socket.connect(Socket.java:633)
            at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
            at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
            at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
            at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
            at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
            at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
            at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
            at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
            at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
            at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
            at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
            at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
            at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
            at com.vaadin.flow.server.frontend.FrontendUtils.getStatsAssetsByChunkName(FrontendUtils.java:580)
            at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.appendNpmBundle(BootstrapHandler.java:972)
            at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:954)
            ... 43 more

**Comment by mvysny** [comment]
Most probably Vaadin was configured for production mode previously, but the stats.json file was deleted and thus Vaadin can't load the production bundle. Can you try running `./gradlew clean run` please? That should correctly reconfigure Vaadin for development mode and should start the server correctly; at least that works on my machine.

**Comment by manitas-manitas** [comment]
Unfortunately it doesnt work with `./gradlew clean run`

I have changed the log level to TRACE

I can see the webpack-de-server is running

    2021-11-10 11:09:57.041 [webpack] DEBUG dev-webpack - (node:31338) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
    2021-11-10 11:09:57.041 [webpack] DEBUG dev-webpack - (Use `node --trace-deprecation ...` to show where the warning was created)
    2021-11-10 11:09:57.048 [webpack] DEBUG dev-webpack - ℹ ｢wds｣: Project is running at http://localhost:56639/webpack-dev-server/
    2021-11-10 11:09:57.048 [webpack] DEBUG dev-webpack - ℹ ｢wds｣: webpack output is served from /VAADIN/
    2021-11-10 11:09:57.048 [webpack] DEBUG dev-webpack - ℹ ｢wds｣: Content not from webpack is served from /Users/manu/IdeaProjects/vaadin14-embedded-jetty-gradle, src/main/webapp
    2021-11-10 11:09:59.112 [webpack] DEBUG dev-webpack - <i> [FlowIdPlugin] Serving the 'stats.json' file dynamically.
    2021-11-10 11:09:59.319 [webpack] DEBUG dev-webpack - ℹ ｢wdm｣: Hash: 77cbdf8bd38a26594266
    2021-11-10 11:09:59.320 [webpack] DEBUG dev-webpack - Version: webpack 4.42.0
    2021-11-10 11:09:59.320 [webpack] DEBUG dev-webpack - Time: 2096ms
    2021-11-10 11:09:59.320 [webpack] DEBUG dev-webpack - Built at: 10/11/2021 11:09:59

it's very stange because I can access it directly in the browser
http://localhost:56639/webpack-dev-server/

and I can also view the dynamically generated stats file in the browser
http://localhost:56639/stats.json

**Comment by mvysny** [comment]
If I understand correctly, then a browser can safely browse to `http://localhost:57803/assetsByChunkName`, but a code in Java such as `new URL("http://localhost:57803/assetsByChunkName").openStream()` would fail with `java.net.ConnectException: Connection refused`? That's certainly very weird. I was thinking that perhaps JVM uses some kind of proxy, but it doesn't look like it. This is certainly very strange...

Found a Vaadin ticket; looks like this is a bug in Vaadin itself. Please see https://github.com/vaadin/flow/issues/12285 for more details.

**Comment by manitas-manitas** [comment]
it did not work with Vaadin 14.7.4

But thanks to the Vaadin ticket you found, I uninstalled Node 17 from my Mac and let the vaadin gradle plugin grab another version and now it works.

It should  be more clear in the Vaadin documentation that there is a compatibilty problem with Node 17

Thanks you so much for your support.
